const coverage = [
  { city: "Rigby", state: "ID" },
  { city: "Andover", state: "MA" },
  { city: "Gilbert", state: "AZ" },
  { city: "Columbia", state: "SC" },
  { city: "St Johnsbury", state: "VT" },
  { city: "Litchfield Park", state: "AZ" },
  { city: "Sun City", state: "AZ" },
  { city: "Sun City West", state: "AZ" },
  { city: "New York", state: "NY" },
  { city: "Hoboken", state: "NJ" },
  { city: "Napa", state: "CA" },
  { city: "Vacaville", state: "CA" },
  { city: "Nashville", state: "TN" },
  { city: "Viroqua", state: "WI" },
  { city: "Holmen", state: "WI" },
  { city: "La Crosse", state: "WI" },
  { city: "Arcadia", state: "WI" },
  { city: "Auburn", state: "WA" },
  { city: "Rock Hill", state: "SC" },
  { city: "Canton", state: "OH" },
  { city: "Chattanooga", state: "TN" },
  { city: "West Orange", state: "NJ" },
  { city: "Annapolis", state: "MD" },
  { city: "Madison", state: "WI" },
  { city: "Sun Prairie", state: "WI" },
  { city: "ST PAUL", state: "MN" },
  { city: "Myrtle Beach", state: "SC" },
  { city: "Moncks Corner", state: "SC" },
  { city: "Summerville", state: "SC" },
  { city: "Chula Vista", state: "CA" },
  { city: "San Diego", state: "CA" },
  { city: "Houston", state: "TX" },
  { city: "Duluth", state: "GA" },
  { city: "Brookhaven", state: "GA" },
  { city: "Johns Creek", state: "GA" },
  { city: "Columbia", state: "SC" },
  { city: "Unit A Arvada", state: "CO" },
  { city: "Falmouth", state: "MA" },
  { city: "Staten Island", state: "NY" },
  { city: "Jersey City", state: "NJ" },
  { city: "Washington", state: "DC" },
  { city: "Clarkston", state: "MI" },
  { city: "Springfield", state: "MO" },
  { city: "Missoula", state: "MT" },
  { city: "Tolland", state: "CT" },
  { city: "Sugar Land", state: "TX" },
  { city: "Marietta", state: "GA" },
  { city: "Clinton", state: "MI" },
  { city: "Crown Point", state: "IN" },
  { city: "Dyer", state: "IN" },
  { city: "Carlstadt", state: "NJ" },
  { city: "Nixa", state: "MO" },
  { city: "Raleigh", state: "NC" },
  { city: "Aldie", state: "VA" },
  { city: "Buffalo", state: "NY" },
  { city: "Cumming", state: "GA" },
  { city: "Granger", state: "IN" },
  { city: "South Bend", state: "IN" },
  { city: "Mishawaka", state: "IN" },
  { city: "Fortson", state: "GA" },
  { city: "Birmingham", state: "AL" },
  { city: "Trussville", state: "AL" },
  { city: "Martinez", state: "GA" },
  { city: "Plano", state: "TX" },
  { city: "Austin", state: "TX" },
  { city: "Eatonton", state: "GA" },
  { city: "Stone Mountain", state: "GA" },
  { city: "Costa Mesa", state: "CA" },
  { city: "Greensburg", state: "PA" },
  { city: "Cresson", state: "PA" },
  { city: "Scottdale", state: "PA" },
  { city: "Indiana", state: "PA" },
  { city: "Miami", state: "FL" },
  { city: "Savannah", state: "GA" },
  { city: "Escondido", state: "CA" },
  { city: "Kannapolis", state: "NC" },
  { city: "New Castle", state: "IN" },
  { city: "Hagerstown", state: "IN" },
  { city: "Lithia Springs", state: "GA" },
  { city: "Feasterville-Trevose", state: "PA" },
  { city: "Johnson City", state: "NY" },
  { city: "Port St. Lucie", state: "FL" },
  { city: "Stuart", state: "FL" },
  { city: "Baltimore", state: "MD" },
  { city: "Glen Allen", state: "VA" },
  { city: "Richmond", state: "VA" },
  { city: "Mint Hill", state: "NC" },
  { city: "Santa Rosa", state: "CA" },
  { city: "Greenville", state: "SC" },
  { city: "Orangeburg", state: "SC" },
  { city: "Florence", state: "SC" },
  { city: "Centennial", state: "CO" },
  { city: "Buford", state: "GA" },
  { city: "Braselton", state: "GA" },
  { city: "Wilmington", state: "DE" },
  { city: "Mayfield Heights", state: "OH" },
  { city: "Maple Grove", state: "MN" },
  { city: "Dacula", state: "GA" },
  { city: "Auburn", state: "GA" },
  { city: "El Paso", state: "TX" }
];